### ISSUE TITLE
Basic HTML improvements

### ISSUE THREAD

**Issue by rngadam** [coderbunker/fcc-leaderboard#1]
* [x] better title
* [x] favicon
* [x] remove google fonts dependencies
* [x] learner 32 is blank

![screen shot 2017-09-19 at 11 33 43 am](https://user-images.githubusercontent.com/538542/30574702-70be8be0-9d2e-11e7-8d4b-f2b6a3b32332.png)

![screen shot 2017-09-19 at 11 34 07 am](https://user-images.githubusercontent.com/538542/30574711-80be51e2-9d2e-11e7-821e-372528325ad4.png)

**Comment by mattermoran** [comment]
fixed
